version: '3.6'
services:
  kusama:
    container_name: 'kusama_node'
    image: polkasource/substrate-client:kusama-latest
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "2"
    volumes:
      - ./data_ksmcc2:/data/chains
    ports:
      - "127.0.0.1:9933:9933"
      - "0.0.0.0:9944:9944"
      - "127.0.0.1:30333:30333"
#    command: ['--light', '--name', 'StarMesh','--out-peers','50','--in-peers','50']
    command: ['--name', 'KodaDot','--out-peers','50','--in-peers','50','--ws-external','--rpc-external','--rpc-cors','all']
